//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//


package com.byldworks.tableau.deploy.api.rest.bindings;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for databaseTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="databaseTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DatabaseServer"/&gt;
 *     &lt;enumeration value="File"/&gt;
 *     &lt;enumeration value="WebDataConnector"/&gt;
 *     &lt;enumeration value="CloudFile"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "databaseTypeType")
@XmlEnum
public enum DatabaseTypeType {

    @XmlEnumValue("DatabaseServer")
    DATABASE_SERVER("DatabaseServer"),
    @XmlEnumValue("File")
    FILE("File"),
    @XmlEnumValue("WebDataConnector")
    WEB_DATA_CONNECTOR("WebDataConnector"),
    @XmlEnumValue("CloudFile")
    CLOUD_FILE("CloudFile");
    private final String value;

    DatabaseTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DatabaseTypeType fromValue(String v) {
        for (DatabaseTypeType c: DatabaseTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
