//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//


package com.byldworks.tableau.deploy.api.rest.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataAccelerationComparisonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataAccelerationComparisonType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="site" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sheetURI" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="unacceleratedSessionCount" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="averageNonAcceleratedPLT" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="acceleratedSessionCount" type="{http://www.w3.org/2001/XMLSchema}long" /&gt;
 *       &lt;attribute name="averageAcceleratedPLT" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataAccelerationComparisonType")
public class DataAccelerationComparisonType {

    @XmlAttribute(name = "site")
    protected String site;
    @XmlAttribute(name = "sheetURI")
    protected String sheetURI;
    @XmlAttribute(name = "unacceleratedSessionCount")
    protected Long unacceleratedSessionCount;
    @XmlAttribute(name = "averageNonAcceleratedPLT")
    protected Double averageNonAcceleratedPLT;
    @XmlAttribute(name = "acceleratedSessionCount")
    protected Long acceleratedSessionCount;
    @XmlAttribute(name = "averageAcceleratedPLT")
    protected Double averageAcceleratedPLT;

    /**
     * Gets the value of the site property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSite() {
        return site;
    }

    /**
     * Sets the value of the site property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSite(String value) {
        this.site = value;
    }

    /**
     * Gets the value of the sheetURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSheetURI() {
        return sheetURI;
    }

    /**
     * Sets the value of the sheetURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSheetURI(String value) {
        this.sheetURI = value;
    }

    /**
     * Gets the value of the unacceleratedSessionCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUnacceleratedSessionCount() {
        return unacceleratedSessionCount;
    }

    /**
     * Sets the value of the unacceleratedSessionCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUnacceleratedSessionCount(Long value) {
        this.unacceleratedSessionCount = value;
    }

    /**
     * Gets the value of the averageNonAcceleratedPLT property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAverageNonAcceleratedPLT() {
        return averageNonAcceleratedPLT;
    }

    /**
     * Sets the value of the averageNonAcceleratedPLT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAverageNonAcceleratedPLT(Double value) {
        this.averageNonAcceleratedPLT = value;
    }

    /**
     * Gets the value of the acceleratedSessionCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAcceleratedSessionCount() {
        return acceleratedSessionCount;
    }

    /**
     * Sets the value of the acceleratedSessionCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAcceleratedSessionCount(Long value) {
        this.acceleratedSessionCount = value;
    }

    /**
     * Gets the value of the averageAcceleratedPLT property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAverageAcceleratedPLT() {
        return averageAcceleratedPLT;
    }

    /**
     * Sets the value of the averageAcceleratedPLT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAverageAcceleratedPLT(Double value) {
        this.averageAcceleratedPLT = value;
    }

}
