//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//


package com.byldworks.tableau.deploy.api.rest.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.byldworks.tableau.deploy.api.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.byldworks.tableau.deploy.api.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FrequencyDetailsType }
     * 
     */
    public FrequencyDetailsType createFrequencyDetailsType() {
        return new FrequencyDetailsType();
    }

    /**
     * Create an instance of {@link GranteeCapabilitiesType }
     * 
     */
    public GranteeCapabilitiesType createGranteeCapabilitiesType() {
        return new GranteeCapabilitiesType();
    }

    /**
     * Create an instance of {@link ViewType }
     * 
     */
    public ViewType createViewType() {
        return new ViewType();
    }

    /**
     * Create an instance of {@link SiteType }
     * 
     */
    public SiteType createSiteType() {
        return new SiteType();
    }

    /**
     * Create an instance of {@link TsRequest }
     * 
     */
    public TsRequest createTsRequest() {
        return new TsRequest();
    }

    /**
     * Create an instance of {@link ColumnType }
     * 
     */
    public ColumnType createColumnType() {
        return new ColumnType();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link ConnectionListType }
     * 
     */
    public ConnectionListType createConnectionListType() {
        return new ConnectionListType();
    }

    /**
     * Create an instance of {@link TableauCredentialsType }
     * 
     */
    public TableauCredentialsType createTableauCredentialsType() {
        return new TableauCredentialsType();
    }

    /**
     * Create an instance of {@link DataAlertType }
     * 
     */
    public DataAlertType createDataAlertType() {
        return new DataAlertType();
    }

    /**
     * Create an instance of {@link DataQualityWarningType }
     * 
     */
    public DataQualityWarningType createDataQualityWarningType() {
        return new DataQualityWarningType();
    }

    /**
     * Create an instance of {@link DataRoleType }
     * 
     */
    public DataRoleType createDataRoleType() {
        return new DataRoleType();
    }

    /**
     * Create an instance of {@link DatabaseType }
     * 
     */
    public DatabaseType createDatabaseType() {
        return new DatabaseType();
    }

    /**
     * Create an instance of {@link DataSourceType }
     * 
     */
    public DataSourceType createDataSourceType() {
        return new DataSourceType();
    }

    /**
     * Create an instance of {@link DistinctValueListType }
     * 
     */
    public DistinctValueListType createDistinctValueListType() {
        return new DistinctValueListType();
    }

    /**
     * Create an instance of {@link FavoriteType }
     * 
     */
    public FavoriteType createFavoriteType() {
        return new FavoriteType();
    }

    /**
     * Create an instance of {@link FieldType }
     * 
     */
    public FieldType createFieldType() {
        return new FieldType();
    }

    /**
     * Create an instance of {@link FieldConceptType }
     * 
     */
    public FieldConceptType createFieldConceptType() {
        return new FieldConceptType();
    }

    /**
     * Create an instance of {@link FlowType }
     * 
     */
    public FlowType createFlowType() {
        return new FlowType();
    }

    /**
     * Create an instance of {@link FlowWarningsListContainerType }
     * 
     */
    public FlowWarningsListContainerType createFlowWarningsListContainerType() {
        return new FlowWarningsListContainerType();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link MetricType }
     * 
     */
    public MetricType createMetricType() {
        return new MetricType();
    }

    /**
     * Create an instance of {@link PermissionsType }
     * 
     */
    public PermissionsType createPermissionsType() {
        return new PermissionsType();
    }

    /**
     * Create an instance of {@link ProjectType }
     * 
     */
    public ProjectType createProjectType() {
        return new ProjectType();
    }

    /**
     * Create an instance of {@link ScheduleType }
     * 
     */
    public ScheduleType createScheduleType() {
        return new ScheduleType();
    }

    /**
     * Create an instance of {@link TableType }
     * 
     */
    public TableType createTableType() {
        return new TableType();
    }

    /**
     * Create an instance of {@link TagListType }
     * 
     */
    public TagListType createTagListType() {
        return new TagListType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link WebhookType }
     * 
     */
    public WebhookType createWebhookType() {
        return new WebhookType();
    }

    /**
     * Create an instance of {@link WorkbookType }
     * 
     */
    public WorkbookType createWorkbookType() {
        return new WorkbookType();
    }

    /**
     * Create an instance of {@link SubscriptionType }
     * 
     */
    public SubscriptionType createSubscriptionType() {
        return new SubscriptionType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link TsResponse }
     * 
     */
    public TsResponse createTsResponse() {
        return new TsResponse();
    }

    /**
     * Create an instance of {@link PaginationType }
     * 
     */
    public PaginationType createPaginationType() {
        return new PaginationType();
    }

    /**
     * Create an instance of {@link ColumnListType }
     * 
     */
    public ColumnListType createColumnListType() {
        return new ColumnListType();
    }

    /**
     * Create an instance of {@link DatabaseListType }
     * 
     */
    public DatabaseListType createDatabaseListType() {
        return new DatabaseListType();
    }

    /**
     * Create an instance of {@link DataSourceListType }
     * 
     */
    public DataSourceListType createDataSourceListType() {
        return new DataSourceListType();
    }

    /**
     * Create an instance of {@link ExtractListType }
     * 
     */
    public ExtractListType createExtractListType() {
        return new ExtractListType();
    }

    /**
     * Create an instance of {@link FlowListType }
     * 
     */
    public FlowListType createFlowListType() {
        return new FlowListType();
    }

    /**
     * Create an instance of {@link FlowOutputStepListType }
     * 
     */
    public FlowOutputStepListType createFlowOutputStepListType() {
        return new FlowOutputStepListType();
    }

    /**
     * Create an instance of {@link GroupListType }
     * 
     */
    public GroupListType createGroupListType() {
        return new GroupListType();
    }

    /**
     * Create an instance of {@link MetricListType }
     * 
     */
    public MetricListType createMetricListType() {
        return new MetricListType();
    }

    /**
     * Create an instance of {@link ProjectListType }
     * 
     */
    public ProjectListType createProjectListType() {
        return new ProjectListType();
    }

    /**
     * Create an instance of {@link RevisionListType }
     * 
     */
    public RevisionListType createRevisionListType() {
        return new RevisionListType();
    }

    /**
     * Create an instance of {@link ScheduleListType }
     * 
     */
    public ScheduleListType createScheduleListType() {
        return new ScheduleListType();
    }

    /**
     * Create an instance of {@link SiteListType }
     * 
     */
    public SiteListType createSiteListType() {
        return new SiteListType();
    }

    /**
     * Create an instance of {@link TableListType }
     * 
     */
    public TableListType createTableListType() {
        return new TableListType();
    }

    /**
     * Create an instance of {@link UserListType }
     * 
     */
    public UserListType createUserListType() {
        return new UserListType();
    }

    /**
     * Create an instance of {@link WorkbookListType }
     * 
     */
    public WorkbookListType createWorkbookListType() {
        return new WorkbookListType();
    }

    /**
     * Create an instance of {@link SubscriptionListType }
     * 
     */
    public SubscriptionListType createSubscriptionListType() {
        return new SubscriptionListType();
    }

    /**
     * Create an instance of {@link BackgroundJobType }
     * 
     */
    public BackgroundJobType createBackgroundJobType() {
        return new BackgroundJobType();
    }

    /**
     * Create an instance of {@link BackgroundJobListType }
     * 
     */
    public BackgroundJobListType createBackgroundJobListType() {
        return new BackgroundJobListType();
    }

    /**
     * Create an instance of {@link DataAccelerationComparisonListType }
     * 
     */
    public DataAccelerationComparisonListType createDataAccelerationComparisonListType() {
        return new DataAccelerationComparisonListType();
    }

    /**
     * Create an instance of {@link DataAlertListType }
     * 
     */
    public DataAlertListType createDataAlertListType() {
        return new DataAlertListType();
    }

    /**
     * Create an instance of {@link DataQualityWarningListType }
     * 
     */
    public DataQualityWarningListType createDataQualityWarningListType() {
        return new DataQualityWarningListType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link FavoriteListType }
     * 
     */
    public FavoriteListType createFavoriteListType() {
        return new FavoriteListType();
    }

    /**
     * Create an instance of {@link FileUploadType }
     * 
     */
    public FileUploadType createFileUploadType() {
        return new FileUploadType();
    }

    /**
     * Create an instance of {@link JobType }
     * 
     */
    public JobType createJobType() {
        return new JobType();
    }

    /**
     * Create an instance of {@link DataAlertsRecipientType }
     * 
     */
    public DataAlertsRecipientType createDataAlertsRecipientType() {
        return new DataAlertsRecipientType();
    }

    /**
     * Create an instance of {@link DataAlertsRecipientListType }
     * 
     */
    public DataAlertsRecipientListType createDataAlertsRecipientListType() {
        return new DataAlertsRecipientListType();
    }

    /**
     * Create an instance of {@link ServerInfo }
     * 
     */
    public ServerInfo createServerInfo() {
        return new ServerInfo();
    }

    /**
     * Create an instance of {@link ServerSettings }
     * 
     */
    public ServerSettings createServerSettings() {
        return new ServerSettings();
    }

    /**
     * Create an instance of {@link ViewListType }
     * 
     */
    public ViewListType createViewListType() {
        return new ViewListType();
    }

    /**
     * Create an instance of {@link WebhookListType }
     * 
     */
    public WebhookListType createWebhookListType() {
        return new WebhookListType();
    }

    /**
     * Create an instance of {@link WebhookTestResultType }
     * 
     */
    public WebhookTestResultType createWebhookTestResultType() {
        return new WebhookTestResultType();
    }

    /**
     * Create an instance of {@link TaskListType }
     * 
     */
    public TaskListType createTaskListType() {
        return new TaskListType();
    }

    /**
     * Create an instance of {@link WarningListType }
     * 
     */
    public WarningListType createWarningListType() {
        return new WarningListType();
    }

    /**
     * Create an instance of {@link DegradationListType }
     * 
     */
    public DegradationListType createDegradationListType() {
        return new DegradationListType();
    }

    /**
     * Create an instance of {@link ListFieldConceptsType }
     * 
     */
    public ListFieldConceptsType createListFieldConceptsType() {
        return new ListFieldConceptsType();
    }

    /**
     * Create an instance of {@link FieldMatchListType }
     * 
     */
    public FieldMatchListType createFieldMatchListType() {
        return new FieldMatchListType();
    }

    /**
     * Create an instance of {@link MatchValuesResultType }
     * 
     */
    public MatchValuesResultType createMatchValuesResultType() {
        return new MatchValuesResultType();
    }

    /**
     * Create an instance of {@link ValueConceptCountType }
     * 
     */
    public ValueConceptCountType createValueConceptCountType() {
        return new ValueConceptCountType();
    }

    /**
     * Create an instance of {@link ListValueConceptsType }
     * 
     */
    public ListValueConceptsType createListValueConceptsType() {
        return new ListValueConceptsType();
    }

    /**
     * Create an instance of {@link IndexingStatusType }
     * 
     */
    public IndexingStatusType createIndexingStatusType() {
        return new IndexingStatusType();
    }

    /**
     * Create an instance of {@link AskDataType }
     * 
     */
    public AskDataType createAskDataType() {
        return new AskDataType();
    }

    /**
     * Create an instance of {@link ConnectionCredentialsType }
     * 
     */
    public ConnectionCredentialsType createConnectionCredentialsType() {
        return new ConnectionCredentialsType();
    }

    /**
     * Create an instance of {@link RevisionType }
     * 
     */
    public RevisionType createRevisionType() {
        return new RevisionType();
    }

    /**
     * Create an instance of {@link ExtractType }
     * 
     */
    public ExtractType createExtractType() {
        return new ExtractType();
    }

    /**
     * Create an instance of {@link ExtractRefreshJobType }
     * 
     */
    public ExtractRefreshJobType createExtractRefreshJobType() {
        return new ExtractRefreshJobType();
    }

    /**
     * Create an instance of {@link RunFlowJobType }
     * 
     */
    public RunFlowJobType createRunFlowJobType() {
        return new RunFlowJobType();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link WebhookDestinationType }
     * 
     */
    public WebhookDestinationType createWebhookDestinationType() {
        return new WebhookDestinationType();
    }

    /**
     * Create an instance of {@link WebhookDestinationHttpType }
     * 
     */
    public WebhookDestinationHttpType createWebhookDestinationHttpType() {
        return new WebhookDestinationHttpType();
    }

    /**
     * Create an instance of {@link WebhookSourceType }
     * 
     */
    public WebhookSourceType createWebhookSourceType() {
        return new WebhookSourceType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventDatasourceCreatedType }
     * 
     */
    public WebhookSourceEventDatasourceCreatedType createWebhookSourceEventDatasourceCreatedType() {
        return new WebhookSourceEventDatasourceCreatedType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventDatasourceDeletedType }
     * 
     */
    public WebhookSourceEventDatasourceDeletedType createWebhookSourceEventDatasourceDeletedType() {
        return new WebhookSourceEventDatasourceDeletedType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventDatasourceRefreshFailedType }
     * 
     */
    public WebhookSourceEventDatasourceRefreshFailedType createWebhookSourceEventDatasourceRefreshFailedType() {
        return new WebhookSourceEventDatasourceRefreshFailedType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventDatasourceRefreshStartedType }
     * 
     */
    public WebhookSourceEventDatasourceRefreshStartedType createWebhookSourceEventDatasourceRefreshStartedType() {
        return new WebhookSourceEventDatasourceRefreshStartedType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventDatasourceRefreshSucceededType }
     * 
     */
    public WebhookSourceEventDatasourceRefreshSucceededType createWebhookSourceEventDatasourceRefreshSucceededType() {
        return new WebhookSourceEventDatasourceRefreshSucceededType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventDatasourceUpdatedType }
     * 
     */
    public WebhookSourceEventDatasourceUpdatedType createWebhookSourceEventDatasourceUpdatedType() {
        return new WebhookSourceEventDatasourceUpdatedType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventWorkbookCreatedType }
     * 
     */
    public WebhookSourceEventWorkbookCreatedType createWebhookSourceEventWorkbookCreatedType() {
        return new WebhookSourceEventWorkbookCreatedType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventWorkbookDeletedType }
     * 
     */
    public WebhookSourceEventWorkbookDeletedType createWebhookSourceEventWorkbookDeletedType() {
        return new WebhookSourceEventWorkbookDeletedType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventWorkbookUpdatedType }
     * 
     */
    public WebhookSourceEventWorkbookUpdatedType createWebhookSourceEventWorkbookUpdatedType() {
        return new WebhookSourceEventWorkbookUpdatedType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventViewDeletedType }
     * 
     */
    public WebhookSourceEventViewDeletedType createWebhookSourceEventViewDeletedType() {
        return new WebhookSourceEventViewDeletedType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventWorkbookRefreshStartedType }
     * 
     */
    public WebhookSourceEventWorkbookRefreshStartedType createWebhookSourceEventWorkbookRefreshStartedType() {
        return new WebhookSourceEventWorkbookRefreshStartedType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventWorkbookRefreshSucceededType }
     * 
     */
    public WebhookSourceEventWorkbookRefreshSucceededType createWebhookSourceEventWorkbookRefreshSucceededType() {
        return new WebhookSourceEventWorkbookRefreshSucceededType();
    }

    /**
     * Create an instance of {@link WebhookSourceEventWorkbookRefreshFailedType }
     * 
     */
    public WebhookSourceEventWorkbookRefreshFailedType createWebhookSourceEventWorkbookRefreshFailedType() {
        return new WebhookSourceEventWorkbookRefreshFailedType();
    }

    /**
     * Create an instance of {@link DegradationType }
     * 
     */
    public DegradationType createDegradationType() {
        return new DegradationType();
    }

    /**
     * Create an instance of {@link FlowOutputStepType }
     * 
     */
    public FlowOutputStepType createFlowOutputStepType() {
        return new FlowOutputStepType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link NameCharacteristicsType }
     * 
     */
    public NameCharacteristicsType createNameCharacteristicsType() {
        return new NameCharacteristicsType();
    }

    /**
     * Create an instance of {@link ValueCharacteristicsType }
     * 
     */
    public ValueCharacteristicsType createValueCharacteristicsType() {
        return new ValueCharacteristicsType();
    }

    /**
     * Create an instance of {@link TextPatternType }
     * 
     */
    public TextPatternType createTextPatternType() {
        return new TextPatternType();
    }

    /**
     * Create an instance of {@link ValueSourceType }
     * 
     */
    public ValueSourceType createValueSourceType() {
        return new ValueSourceType();
    }

    /**
     * Create an instance of {@link DataSourceValueStoreType }
     * 
     */
    public DataSourceValueStoreType createDataSourceValueStoreType() {
        return new DataSourceValueStoreType();
    }

    /**
     * Create an instance of {@link DistinctValueType }
     * 
     */
    public DistinctValueType createDistinctValueType() {
        return new DistinctValueType();
    }

    /**
     * Create an instance of {@link SemanticsValueType }
     * 
     */
    public SemanticsValueType createSemanticsValueType() {
        return new SemanticsValueType();
    }

    /**
     * Create an instance of {@link FieldMatchType }
     * 
     */
    public FieldMatchType createFieldMatchType() {
        return new FieldMatchType();
    }

    /**
     * Create an instance of {@link ValueMatchType }
     * 
     */
    public ValueMatchType createValueMatchType() {
        return new ValueMatchType();
    }

    /**
     * Create an instance of {@link ValueConceptType }
     * 
     */
    public ValueConceptType createValueConceptType() {
        return new ValueConceptType();
    }

    /**
     * Create an instance of {@link CapabilityType }
     * 
     */
    public CapabilityType createCapabilityType() {
        return new CapabilityType();
    }

    /**
     * Create an instance of {@link DomainDirectiveType }
     * 
     */
    public DomainDirectiveType createDomainDirectiveType() {
        return new DomainDirectiveType();
    }

    /**
     * Create an instance of {@link ImportDirectiveType }
     * 
     */
    public ImportDirectiveType createImportDirectiveType() {
        return new ImportDirectiveType();
    }

    /**
     * Create an instance of {@link StatusNoteListType }
     * 
     */
    public StatusNoteListType createStatusNoteListType() {
        return new StatusNoteListType();
    }

    /**
     * Create an instance of {@link StatusNoteType }
     * 
     */
    public StatusNoteType createStatusNoteType() {
        return new StatusNoteType();
    }

    /**
     * Create an instance of {@link ParentType }
     * 
     */
    public ParentType createParentType() {
        return new ParentType();
    }

    /**
     * Create an instance of {@link IntervalType }
     * 
     */
    public IntervalType createIntervalType() {
        return new IntervalType();
    }

    /**
     * Create an instance of {@link SubscriptionContentType }
     * 
     */
    public SubscriptionContentType createSubscriptionContentType() {
        return new SubscriptionContentType();
    }

    /**
     * Create an instance of {@link ProductVersion }
     * 
     */
    public ProductVersion createProductVersion() {
        return new ProductVersion();
    }

    /**
     * Create an instance of {@link TaskRunFlowType }
     * 
     */
    public TaskRunFlowType createTaskRunFlowType() {
        return new TaskRunFlowType();
    }

    /**
     * Create an instance of {@link TaskExtractRefreshType }
     * 
     */
    public TaskExtractRefreshType createTaskExtractRefreshType() {
        return new TaskExtractRefreshType();
    }

    /**
     * Create an instance of {@link TaskDataAccelerationType }
     * 
     */
    public TaskDataAccelerationType createTaskDataAccelerationType() {
        return new TaskDataAccelerationType();
    }

    /**
     * Create an instance of {@link WarningType }
     * 
     */
    public WarningType createWarningType() {
        return new WarningType();
    }

    /**
     * Create an instance of {@link DataAccelerationInfoType }
     * 
     */
    public DataAccelerationInfoType createDataAccelerationInfoType() {
        return new DataAccelerationInfoType();
    }

    /**
     * Create an instance of {@link DataAccelerationComparisonType }
     * 
     */
    public DataAccelerationComparisonType createDataAccelerationComparisonType() {
        return new DataAccelerationComparisonType();
    }

    /**
     * Create an instance of {@link FrequencyDetailsType.Intervals }
     * 
     */
    public FrequencyDetailsType.Intervals createFrequencyDetailsTypeIntervals() {
        return new FrequencyDetailsType.Intervals();
    }

    /**
     * Create an instance of {@link GranteeCapabilitiesType.Capabilities }
     * 
     */
    public GranteeCapabilitiesType.Capabilities createGranteeCapabilitiesTypeCapabilities() {
        return new GranteeCapabilitiesType.Capabilities();
    }

    /**
     * Create an instance of {@link ViewType.Usage }
     * 
     */
    public ViewType.Usage createViewTypeUsage() {
        return new ViewType.Usage();
    }

    /**
     * Create an instance of {@link SiteType.Usage }
     * 
     */
    public SiteType.Usage createSiteTypeUsage() {
        return new SiteType.Usage();
    }

}
