//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tableau.com/api", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.byldworks.tableau.deploy.api.rest.bindings;
