//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//


package com.byldworks.tableau.deploy.api.rest.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serverSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="serverSettings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="oAuthEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="sheetImageMaxAgeFloor" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="sheetImageMaxAgeCeiling" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="offlineInteractionSupportedPhase" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serverSettings", propOrder = {
    "oAuthEnabled",
    "sheetImageMaxAgeFloor",
    "sheetImageMaxAgeCeiling",
    "offlineInteractionSupportedPhase"
})
public class ServerSettings {

    protected boolean oAuthEnabled;
    protected int sheetImageMaxAgeFloor;
    protected int sheetImageMaxAgeCeiling;
    protected int offlineInteractionSupportedPhase;

    /**
     * Gets the value of the oAuthEnabled property.
     * 
     */
    public boolean isOAuthEnabled() {
        return oAuthEnabled;
    }

    /**
     * Sets the value of the oAuthEnabled property.
     * 
     */
    public void setOAuthEnabled(boolean value) {
        this.oAuthEnabled = value;
    }

    /**
     * Gets the value of the sheetImageMaxAgeFloor property.
     * 
     */
    public int getSheetImageMaxAgeFloor() {
        return sheetImageMaxAgeFloor;
    }

    /**
     * Sets the value of the sheetImageMaxAgeFloor property.
     * 
     */
    public void setSheetImageMaxAgeFloor(int value) {
        this.sheetImageMaxAgeFloor = value;
    }

    /**
     * Gets the value of the sheetImageMaxAgeCeiling property.
     * 
     */
    public int getSheetImageMaxAgeCeiling() {
        return sheetImageMaxAgeCeiling;
    }

    /**
     * Sets the value of the sheetImageMaxAgeCeiling property.
     * 
     */
    public void setSheetImageMaxAgeCeiling(int value) {
        this.sheetImageMaxAgeCeiling = value;
    }

    /**
     * Gets the value of the offlineInteractionSupportedPhase property.
     * 
     */
    public int getOfflineInteractionSupportedPhase() {
        return offlineInteractionSupportedPhase;
    }

    /**
     * Sets the value of the offlineInteractionSupportedPhase property.
     * 
     */
    public void setOfflineInteractionSupportedPhase(int value) {
        this.offlineInteractionSupportedPhase = value;
    }

}
