//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//


package com.byldworks.tableau.deploy.api.rest.bindings;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for siteRoleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="siteRoleType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Creator"/&gt;
 *     &lt;enumeration value="Explorer"/&gt;
 *     &lt;enumeration value="ExplorerCanPublish"/&gt;
 *     &lt;enumeration value="Guest"/&gt;
 *     &lt;enumeration value="Interactor"/&gt;
 *     &lt;enumeration value="Publisher"/&gt;
 *     &lt;enumeration value="ReadOnly"/&gt;
 *     &lt;enumeration value="ServerAdministrator"/&gt;
 *     &lt;enumeration value="SiteAdministrator"/&gt;
 *     &lt;enumeration value="SiteAdministratorCreator"/&gt;
 *     &lt;enumeration value="SiteAdministratorExplorer"/&gt;
 *     &lt;enumeration value="Unlicensed"/&gt;
 *     &lt;enumeration value="UnlicensedWithPublish"/&gt;
 *     &lt;enumeration value="Viewer"/&gt;
 *     &lt;enumeration value="ViewerWithPublish"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "siteRoleType")
@XmlEnum
public enum SiteRoleType {

    @XmlEnumValue("Creator")
    CREATOR("Creator"),
    @XmlEnumValue("Explorer")
    EXPLORER("Explorer"),
    @XmlEnumValue("ExplorerCanPublish")
    EXPLORER_CAN_PUBLISH("ExplorerCanPublish"),
    @XmlEnumValue("Guest")
    GUEST("Guest"),
    @XmlEnumValue("Interactor")
    INTERACTOR("Interactor"),
    @XmlEnumValue("Publisher")
    PUBLISHER("Publisher"),
    @XmlEnumValue("ReadOnly")
    READ_ONLY("ReadOnly"),
    @XmlEnumValue("ServerAdministrator")
    SERVER_ADMINISTRATOR("ServerAdministrator"),
    @XmlEnumValue("SiteAdministrator")
    SITE_ADMINISTRATOR("SiteAdministrator"),
    @XmlEnumValue("SiteAdministratorCreator")
    SITE_ADMINISTRATOR_CREATOR("SiteAdministratorCreator"),
    @XmlEnumValue("SiteAdministratorExplorer")
    SITE_ADMINISTRATOR_EXPLORER("SiteAdministratorExplorer"),
    @XmlEnumValue("Unlicensed")
    UNLICENSED("Unlicensed"),
    @XmlEnumValue("UnlicensedWithPublish")
    UNLICENSED_WITH_PUBLISH("UnlicensedWithPublish"),
    @XmlEnumValue("Viewer")
    VIEWER("Viewer"),
    @XmlEnumValue("ViewerWithPublish")
    VIEWER_WITH_PUBLISH("ViewerWithPublish");
    private final String value;

    SiteRoleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SiteRoleType fromValue(String v) {
        for (SiteRoleType c: SiteRoleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
