//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//


package com.byldworks.tableau.deploy.api.rest.bindings;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for siteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="siteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="usage" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="numUsers" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *                 &lt;attribute name="numCreators" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *                 &lt;attribute name="numExplorers" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *                 &lt;attribute name="numViewers" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *                 &lt;attribute name="storage" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://tableau.com/api}resourceIdType" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="contentUrl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="adminMode"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="ContentOnly"/&gt;
 *             &lt;enumeration value="ContentAndUsers"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="userQuota" type="{http://tableau.com/api}siteQuotaType" /&gt;
 *       &lt;attribute name="storageQuota" type="{http://tableau.com/api}siteQuotaType" /&gt;
 *       &lt;attribute name="tierCreatorCapacity" type="{http://tableau.com/api}siteCapacityType" /&gt;
 *       &lt;attribute name="tierExplorerCapacity" type="{http://tableau.com/api}siteCapacityType" /&gt;
 *       &lt;attribute name="tierViewerCapacity" type="{http://tableau.com/api}siteCapacityType" /&gt;
 *       &lt;attribute name="disableSubscriptions" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="state" type="{http://tableau.com/api}stateType" /&gt;
 *       &lt;attribute name="revisionHistoryEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="revisionLimit" type="{http://tableau.com/api}revisionLimitType" /&gt;
 *       &lt;attribute name="subscribeOthersEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="allowSubscriptionAttachments" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="guestAccessEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="cacheWarmupEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="dataAlertsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="commentingEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="commentingMentionsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="cacheeWarmupThreshold" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="flowsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="extractEncryptionMode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="dataAccelerationMode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mobileBiometricsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="sheetImageEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="catalogingEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="derivedPermissionsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="askDataMode"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="EnabledByDefault"/&gt;
 *             &lt;enumeration value="DisabledByDefault"/&gt;
 *             &lt;enumeration value="DisabledAlways"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="authoringEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="customSubscriptionEmailEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="customSubscriptionEmail" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="customSubscriptionFooterEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="customSubscriptionFooter" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="userVisibilityMode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="requestAccessEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="catalogObfuscationEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="flowAutoSaveEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="webExtractionEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="runNowEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="metricsContentTypeEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="notifySiteAdminsOnThrottle" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="namedSharingEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "siteType", propOrder = {
    "usage"
})
public class SiteType {

    protected Usage usage;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "contentUrl")
    protected String contentUrl;
    @XmlAttribute(name = "adminMode")
    protected String adminMode;
    @XmlAttribute(name = "userQuota")
    protected BigInteger userQuota;
    @XmlAttribute(name = "storageQuota")
    protected BigInteger storageQuota;
    @XmlAttribute(name = "tierCreatorCapacity")
    protected BigInteger tierCreatorCapacity;
    @XmlAttribute(name = "tierExplorerCapacity")
    protected BigInteger tierExplorerCapacity;
    @XmlAttribute(name = "tierViewerCapacity")
    protected BigInteger tierViewerCapacity;
    @XmlAttribute(name = "disableSubscriptions")
    protected Boolean disableSubscriptions;
    @XmlAttribute(name = "state")
    protected StateType state;
    @XmlAttribute(name = "revisionHistoryEnabled")
    protected Boolean revisionHistoryEnabled;
    @XmlAttribute(name = "revisionLimit")
    protected String revisionLimit;
    @XmlAttribute(name = "subscribeOthersEnabled")
    protected Boolean subscribeOthersEnabled;
    @XmlAttribute(name = "allowSubscriptionAttachments")
    protected Boolean allowSubscriptionAttachments;
    @XmlAttribute(name = "guestAccessEnabled")
    protected Boolean guestAccessEnabled;
    @XmlAttribute(name = "cacheWarmupEnabled")
    protected Boolean cacheWarmupEnabled;
    @XmlAttribute(name = "dataAlertsEnabled")
    protected Boolean dataAlertsEnabled;
    @XmlAttribute(name = "commentingEnabled")
    protected Boolean commentingEnabled;
    @XmlAttribute(name = "commentingMentionsEnabled")
    protected Boolean commentingMentionsEnabled;
    @XmlAttribute(name = "cacheeWarmupThreshold")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger cacheeWarmupThreshold;
    @XmlAttribute(name = "flowsEnabled")
    protected Boolean flowsEnabled;
    @XmlAttribute(name = "extractEncryptionMode")
    protected String extractEncryptionMode;
    @XmlAttribute(name = "dataAccelerationMode")
    protected String dataAccelerationMode;
    @XmlAttribute(name = "mobileBiometricsEnabled")
    protected Boolean mobileBiometricsEnabled;
    @XmlAttribute(name = "sheetImageEnabled")
    protected Boolean sheetImageEnabled;
    @XmlAttribute(name = "catalogingEnabled")
    protected Boolean catalogingEnabled;
    @XmlAttribute(name = "derivedPermissionsEnabled")
    protected Boolean derivedPermissionsEnabled;
    @XmlAttribute(name = "askDataMode")
    protected String askDataMode;
    @XmlAttribute(name = "authoringEnabled")
    protected Boolean authoringEnabled;
    @XmlAttribute(name = "customSubscriptionEmailEnabled")
    protected Boolean customSubscriptionEmailEnabled;
    @XmlAttribute(name = "customSubscriptionEmail")
    protected String customSubscriptionEmail;
    @XmlAttribute(name = "customSubscriptionFooterEnabled")
    protected Boolean customSubscriptionFooterEnabled;
    @XmlAttribute(name = "customSubscriptionFooter")
    protected String customSubscriptionFooter;
    @XmlAttribute(name = "userVisibilityMode")
    protected String userVisibilityMode;
    @XmlAttribute(name = "requestAccessEnabled")
    protected Boolean requestAccessEnabled;
    @XmlAttribute(name = "catalogObfuscationEnabled")
    protected Boolean catalogObfuscationEnabled;
    @XmlAttribute(name = "flowAutoSaveEnabled")
    protected Boolean flowAutoSaveEnabled;
    @XmlAttribute(name = "webExtractionEnabled")
    protected Boolean webExtractionEnabled;
    @XmlAttribute(name = "runNowEnabled")
    protected Boolean runNowEnabled;
    @XmlAttribute(name = "metricsContentTypeEnabled")
    protected Boolean metricsContentTypeEnabled;
    @XmlAttribute(name = "notifySiteAdminsOnThrottle")
    protected Boolean notifySiteAdminsOnThrottle;
    @XmlAttribute(name = "namedSharingEnabled")
    protected Boolean namedSharingEnabled;

    /**
     * Gets the value of the usage property.
     * 
     * @return
     *     possible object is
     *     {@link Usage }
     *     
     */
    public Usage getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Usage }
     *     
     */
    public void setUsage(Usage value) {
        this.usage = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the contentUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentUrl() {
        return contentUrl;
    }

    /**
     * Sets the value of the contentUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentUrl(String value) {
        this.contentUrl = value;
    }

    /**
     * Gets the value of the adminMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminMode() {
        return adminMode;
    }

    /**
     * Sets the value of the adminMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminMode(String value) {
        this.adminMode = value;
    }

    /**
     * Gets the value of the userQuota property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserQuota() {
        return userQuota;
    }

    /**
     * Sets the value of the userQuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserQuota(BigInteger value) {
        this.userQuota = value;
    }

    /**
     * Gets the value of the storageQuota property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStorageQuota() {
        return storageQuota;
    }

    /**
     * Sets the value of the storageQuota property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStorageQuota(BigInteger value) {
        this.storageQuota = value;
    }

    /**
     * Gets the value of the tierCreatorCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTierCreatorCapacity() {
        return tierCreatorCapacity;
    }

    /**
     * Sets the value of the tierCreatorCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTierCreatorCapacity(BigInteger value) {
        this.tierCreatorCapacity = value;
    }

    /**
     * Gets the value of the tierExplorerCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTierExplorerCapacity() {
        return tierExplorerCapacity;
    }

    /**
     * Sets the value of the tierExplorerCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTierExplorerCapacity(BigInteger value) {
        this.tierExplorerCapacity = value;
    }

    /**
     * Gets the value of the tierViewerCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTierViewerCapacity() {
        return tierViewerCapacity;
    }

    /**
     * Sets the value of the tierViewerCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTierViewerCapacity(BigInteger value) {
        this.tierViewerCapacity = value;
    }

    /**
     * Gets the value of the disableSubscriptions property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisableSubscriptions() {
        return disableSubscriptions;
    }

    /**
     * Sets the value of the disableSubscriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisableSubscriptions(Boolean value) {
        this.disableSubscriptions = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link StateType }
     *     
     */
    public StateType getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateType }
     *     
     */
    public void setState(StateType value) {
        this.state = value;
    }

    /**
     * Gets the value of the revisionHistoryEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRevisionHistoryEnabled() {
        return revisionHistoryEnabled;
    }

    /**
     * Sets the value of the revisionHistoryEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRevisionHistoryEnabled(Boolean value) {
        this.revisionHistoryEnabled = value;
    }

    /**
     * Gets the value of the revisionLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionLimit() {
        return revisionLimit;
    }

    /**
     * Sets the value of the revisionLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionLimit(String value) {
        this.revisionLimit = value;
    }

    /**
     * Gets the value of the subscribeOthersEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSubscribeOthersEnabled() {
        return subscribeOthersEnabled;
    }

    /**
     * Sets the value of the subscribeOthersEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSubscribeOthersEnabled(Boolean value) {
        this.subscribeOthersEnabled = value;
    }

    /**
     * Gets the value of the allowSubscriptionAttachments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowSubscriptionAttachments() {
        return allowSubscriptionAttachments;
    }

    /**
     * Sets the value of the allowSubscriptionAttachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowSubscriptionAttachments(Boolean value) {
        this.allowSubscriptionAttachments = value;
    }

    /**
     * Gets the value of the guestAccessEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGuestAccessEnabled() {
        return guestAccessEnabled;
    }

    /**
     * Sets the value of the guestAccessEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGuestAccessEnabled(Boolean value) {
        this.guestAccessEnabled = value;
    }

    /**
     * Gets the value of the cacheWarmupEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCacheWarmupEnabled() {
        return cacheWarmupEnabled;
    }

    /**
     * Sets the value of the cacheWarmupEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCacheWarmupEnabled(Boolean value) {
        this.cacheWarmupEnabled = value;
    }

    /**
     * Gets the value of the dataAlertsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDataAlertsEnabled() {
        return dataAlertsEnabled;
    }

    /**
     * Sets the value of the dataAlertsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDataAlertsEnabled(Boolean value) {
        this.dataAlertsEnabled = value;
    }

    /**
     * Gets the value of the commentingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCommentingEnabled() {
        return commentingEnabled;
    }

    /**
     * Sets the value of the commentingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCommentingEnabled(Boolean value) {
        this.commentingEnabled = value;
    }

    /**
     * Gets the value of the commentingMentionsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCommentingMentionsEnabled() {
        return commentingMentionsEnabled;
    }

    /**
     * Sets the value of the commentingMentionsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCommentingMentionsEnabled(Boolean value) {
        this.commentingMentionsEnabled = value;
    }

    /**
     * Gets the value of the cacheeWarmupThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCacheeWarmupThreshold() {
        return cacheeWarmupThreshold;
    }

    /**
     * Sets the value of the cacheeWarmupThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCacheeWarmupThreshold(BigInteger value) {
        this.cacheeWarmupThreshold = value;
    }

    /**
     * Gets the value of the flowsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFlowsEnabled() {
        return flowsEnabled;
    }

    /**
     * Sets the value of the flowsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFlowsEnabled(Boolean value) {
        this.flowsEnabled = value;
    }

    /**
     * Gets the value of the extractEncryptionMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtractEncryptionMode() {
        return extractEncryptionMode;
    }

    /**
     * Sets the value of the extractEncryptionMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtractEncryptionMode(String value) {
        this.extractEncryptionMode = value;
    }

    /**
     * Gets the value of the dataAccelerationMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataAccelerationMode() {
        return dataAccelerationMode;
    }

    /**
     * Sets the value of the dataAccelerationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataAccelerationMode(String value) {
        this.dataAccelerationMode = value;
    }

    /**
     * Gets the value of the mobileBiometricsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMobileBiometricsEnabled() {
        return mobileBiometricsEnabled;
    }

    /**
     * Sets the value of the mobileBiometricsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMobileBiometricsEnabled(Boolean value) {
        this.mobileBiometricsEnabled = value;
    }

    /**
     * Gets the value of the sheetImageEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSheetImageEnabled() {
        return sheetImageEnabled;
    }

    /**
     * Sets the value of the sheetImageEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSheetImageEnabled(Boolean value) {
        this.sheetImageEnabled = value;
    }

    /**
     * Gets the value of the catalogingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCatalogingEnabled() {
        return catalogingEnabled;
    }

    /**
     * Sets the value of the catalogingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCatalogingEnabled(Boolean value) {
        this.catalogingEnabled = value;
    }

    /**
     * Gets the value of the derivedPermissionsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDerivedPermissionsEnabled() {
        return derivedPermissionsEnabled;
    }

    /**
     * Sets the value of the derivedPermissionsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDerivedPermissionsEnabled(Boolean value) {
        this.derivedPermissionsEnabled = value;
    }

    /**
     * Gets the value of the askDataMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAskDataMode() {
        return askDataMode;
    }

    /**
     * Sets the value of the askDataMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAskDataMode(String value) {
        this.askDataMode = value;
    }

    /**
     * Gets the value of the authoringEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAuthoringEnabled() {
        return authoringEnabled;
    }

    /**
     * Sets the value of the authoringEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAuthoringEnabled(Boolean value) {
        this.authoringEnabled = value;
    }

    /**
     * Gets the value of the customSubscriptionEmailEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCustomSubscriptionEmailEnabled() {
        return customSubscriptionEmailEnabled;
    }

    /**
     * Sets the value of the customSubscriptionEmailEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCustomSubscriptionEmailEnabled(Boolean value) {
        this.customSubscriptionEmailEnabled = value;
    }

    /**
     * Gets the value of the customSubscriptionEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomSubscriptionEmail() {
        return customSubscriptionEmail;
    }

    /**
     * Sets the value of the customSubscriptionEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomSubscriptionEmail(String value) {
        this.customSubscriptionEmail = value;
    }

    /**
     * Gets the value of the customSubscriptionFooterEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCustomSubscriptionFooterEnabled() {
        return customSubscriptionFooterEnabled;
    }

    /**
     * Sets the value of the customSubscriptionFooterEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCustomSubscriptionFooterEnabled(Boolean value) {
        this.customSubscriptionFooterEnabled = value;
    }

    /**
     * Gets the value of the customSubscriptionFooter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomSubscriptionFooter() {
        return customSubscriptionFooter;
    }

    /**
     * Sets the value of the customSubscriptionFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomSubscriptionFooter(String value) {
        this.customSubscriptionFooter = value;
    }

    /**
     * Gets the value of the userVisibilityMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserVisibilityMode() {
        return userVisibilityMode;
    }

    /**
     * Sets the value of the userVisibilityMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserVisibilityMode(String value) {
        this.userVisibilityMode = value;
    }

    /**
     * Gets the value of the requestAccessEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequestAccessEnabled() {
        return requestAccessEnabled;
    }

    /**
     * Sets the value of the requestAccessEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequestAccessEnabled(Boolean value) {
        this.requestAccessEnabled = value;
    }

    /**
     * Gets the value of the catalogObfuscationEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCatalogObfuscationEnabled() {
        return catalogObfuscationEnabled;
    }

    /**
     * Sets the value of the catalogObfuscationEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCatalogObfuscationEnabled(Boolean value) {
        this.catalogObfuscationEnabled = value;
    }

    /**
     * Gets the value of the flowAutoSaveEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFlowAutoSaveEnabled() {
        return flowAutoSaveEnabled;
    }

    /**
     * Sets the value of the flowAutoSaveEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFlowAutoSaveEnabled(Boolean value) {
        this.flowAutoSaveEnabled = value;
    }

    /**
     * Gets the value of the webExtractionEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWebExtractionEnabled() {
        return webExtractionEnabled;
    }

    /**
     * Sets the value of the webExtractionEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWebExtractionEnabled(Boolean value) {
        this.webExtractionEnabled = value;
    }

    /**
     * Gets the value of the runNowEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRunNowEnabled() {
        return runNowEnabled;
    }

    /**
     * Sets the value of the runNowEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRunNowEnabled(Boolean value) {
        this.runNowEnabled = value;
    }

    /**
     * Gets the value of the metricsContentTypeEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMetricsContentTypeEnabled() {
        return metricsContentTypeEnabled;
    }

    /**
     * Sets the value of the metricsContentTypeEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMetricsContentTypeEnabled(Boolean value) {
        this.metricsContentTypeEnabled = value;
    }

    /**
     * Gets the value of the notifySiteAdminsOnThrottle property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNotifySiteAdminsOnThrottle() {
        return notifySiteAdminsOnThrottle;
    }

    /**
     * Sets the value of the notifySiteAdminsOnThrottle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNotifySiteAdminsOnThrottle(Boolean value) {
        this.notifySiteAdminsOnThrottle = value;
    }

    /**
     * Gets the value of the namedSharingEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNamedSharingEnabled() {
        return namedSharingEnabled;
    }

    /**
     * Sets the value of the namedSharingEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNamedSharingEnabled(Boolean value) {
        this.namedSharingEnabled = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="numUsers" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
     *       &lt;attribute name="numCreators" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
     *       &lt;attribute name="numExplorers" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
     *       &lt;attribute name="numViewers" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
     *       &lt;attribute name="storage" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Usage {

        @XmlAttribute(name = "numUsers", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger numUsers;
        @XmlAttribute(name = "numCreators")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger numCreators;
        @XmlAttribute(name = "numExplorers")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger numExplorers;
        @XmlAttribute(name = "numViewers")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger numViewers;
        @XmlAttribute(name = "storage", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger storage;

        /**
         * Gets the value of the numUsers property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumUsers() {
            return numUsers;
        }

        /**
         * Sets the value of the numUsers property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumUsers(BigInteger value) {
            this.numUsers = value;
        }

        /**
         * Gets the value of the numCreators property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumCreators() {
            return numCreators;
        }

        /**
         * Sets the value of the numCreators property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumCreators(BigInteger value) {
            this.numCreators = value;
        }

        /**
         * Gets the value of the numExplorers property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumExplorers() {
            return numExplorers;
        }

        /**
         * Sets the value of the numExplorers property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumExplorers(BigInteger value) {
            this.numExplorers = value;
        }

        /**
         * Gets the value of the numViewers property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumViewers() {
            return numViewers;
        }

        /**
         * Sets the value of the numViewers property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumViewers(BigInteger value) {
            this.numViewers = value;
        }

        /**
         * Gets the value of the storage property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getStorage() {
            return storage;
        }

        /**
         * Sets the value of the storage property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setStorage(BigInteger value) {
            this.storage = value;
        }

    }

}
