//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//


package com.byldworks.tableau.deploy.api.rest.bindings;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for siteUserAuthSettingType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="siteUserAuthSettingType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ServerDefault"/&gt;
 *     &lt;enumeration value="SAML"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "siteUserAuthSettingType")
@XmlEnum
public enum SiteUserAuthSettingType {

    @XmlEnumValue("ServerDefault")
    SERVER_DEFAULT("ServerDefault"),
    SAML("SAML");
    private final String value;

    SiteUserAuthSettingType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SiteUserAuthSettingType fromValue(String v) {
        for (SiteUserAuthSettingType c: SiteUserAuthSettingType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
