//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//


package com.byldworks.tableau.deploy.api.rest.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="column" type="{http://tableau.com/api}columnType"/&gt;
 *         &lt;element name="connection" type="{http://tableau.com/api}connectionType"/&gt;
 *         &lt;element name="connections" type="{http://tableau.com/api}connectionListType"/&gt;
 *         &lt;element name="credentials" type="{http://tableau.com/api}tableauCredentialsType"/&gt;
 *         &lt;element name="dataAlert" type="{http://tableau.com/api}dataAlertType"/&gt;
 *         &lt;element name="dataQualityWarning" type="{http://tableau.com/api}dataQualityWarningType"/&gt;
 *         &lt;element name="dataRole" type="{http://tableau.com/api}dataRoleType"/&gt;
 *         &lt;element name="database" type="{http://tableau.com/api}databaseType"/&gt;
 *         &lt;element name="datasource" type="{http://tableau.com/api}dataSourceType"/&gt;
 *         &lt;element name="distinctValues" type="{http://tableau.com/api}distinctValueListType"/&gt;
 *         &lt;element name="favorite" type="{http://tableau.com/api}favoriteType"/&gt;
 *         &lt;element name="field" type="{http://tableau.com/api}fieldType"/&gt;
 *         &lt;element name="fieldConcept" type="{http://tableau.com/api}fieldConceptType"/&gt;
 *         &lt;element name="flow" type="{http://tableau.com/api}flowType"/&gt;
 *         &lt;element name="flowWarnings" type="{http://tableau.com/api}flowWarningsListContainerType"/&gt;
 *         &lt;element name="group" type="{http://tableau.com/api}groupType"/&gt;
 *         &lt;element name="metric" type="{http://tableau.com/api}metricType"/&gt;
 *         &lt;element name="permissions" type="{http://tableau.com/api}permissionsType"/&gt;
 *         &lt;element name="project" type="{http://tableau.com/api}projectType"/&gt;
 *         &lt;element name="schedule" type="{http://tableau.com/api}scheduleType"/&gt;
 *         &lt;element name="site" type="{http://tableau.com/api}siteType"/&gt;
 *         &lt;element name="table" type="{http://tableau.com/api}tableType"/&gt;
 *         &lt;element name="tags" type="{http://tableau.com/api}tagListType"/&gt;
 *         &lt;element name="user" type="{http://tableau.com/api}userType"/&gt;
 *         &lt;element name="webhook" type="{http://tableau.com/api}webhookType"/&gt;
 *         &lt;element name="workbook" type="{http://tableau.com/api}workbookType"/&gt;
 *         &lt;element name="subscription" type="{http://tableau.com/api}subscriptionType"/&gt;
 *         &lt;element name="task" type="{http://tableau.com/api}taskType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "column",
    "connection",
    "connections",
    "credentials",
    "dataAlert",
    "dataQualityWarning",
    "dataRole",
    "database",
    "datasource",
    "distinctValues",
    "favorite",
    "field",
    "fieldConcept",
    "flow",
    "flowWarnings",
    "group",
    "metric",
    "permissions",
    "project",
    "schedule",
    "site",
    "table",
    "tags",
    "user",
    "webhook",
    "workbook",
    "subscription",
    "task"
})
@XmlRootElement(name = "tsRequest")
public class TsRequest {

    protected ColumnType column;
    protected ConnectionType connection;
    protected ConnectionListType connections;
    protected TableauCredentialsType credentials;
    protected DataAlertType dataAlert;
    protected DataQualityWarningType dataQualityWarning;
    protected DataRoleType dataRole;
    protected DatabaseType database;
    protected DataSourceType datasource;
    protected DistinctValueListType distinctValues;
    protected FavoriteType favorite;
    protected FieldType field;
    protected FieldConceptType fieldConcept;
    protected FlowType flow;
    protected FlowWarningsListContainerType flowWarnings;
    protected GroupType group;
    protected MetricType metric;
    protected PermissionsType permissions;
    protected ProjectType project;
    protected ScheduleType schedule;
    protected SiteType site;
    protected TableType table;
    protected TagListType tags;
    protected UserType user;
    protected WebhookType webhook;
    protected WorkbookType workbook;
    protected SubscriptionType subscription;
    protected TaskType task;

    /**
     * Gets the value of the column property.
     * 
     * @return
     *     possible object is
     *     {@link ColumnType }
     *     
     */
    public ColumnType getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColumnType }
     *     
     */
    public void setColumn(ColumnType value) {
        this.column = value;
    }

    /**
     * Gets the value of the connection property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionType }
     *     
     */
    public ConnectionType getConnection() {
        return connection;
    }

    /**
     * Sets the value of the connection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionType }
     *     
     */
    public void setConnection(ConnectionType value) {
        this.connection = value;
    }

    /**
     * Gets the value of the connections property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionListType }
     *     
     */
    public ConnectionListType getConnections() {
        return connections;
    }

    /**
     * Sets the value of the connections property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionListType }
     *     
     */
    public void setConnections(ConnectionListType value) {
        this.connections = value;
    }

    /**
     * Gets the value of the credentials property.
     * 
     * @return
     *     possible object is
     *     {@link TableauCredentialsType }
     *     
     */
    public TableauCredentialsType getCredentials() {
        return credentials;
    }

    /**
     * Sets the value of the credentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableauCredentialsType }
     *     
     */
    public void setCredentials(TableauCredentialsType value) {
        this.credentials = value;
    }

    /**
     * Gets the value of the dataAlert property.
     * 
     * @return
     *     possible object is
     *     {@link DataAlertType }
     *     
     */
    public DataAlertType getDataAlert() {
        return dataAlert;
    }

    /**
     * Sets the value of the dataAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataAlertType }
     *     
     */
    public void setDataAlert(DataAlertType value) {
        this.dataAlert = value;
    }

    /**
     * Gets the value of the dataQualityWarning property.
     * 
     * @return
     *     possible object is
     *     {@link DataQualityWarningType }
     *     
     */
    public DataQualityWarningType getDataQualityWarning() {
        return dataQualityWarning;
    }

    /**
     * Sets the value of the dataQualityWarning property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataQualityWarningType }
     *     
     */
    public void setDataQualityWarning(DataQualityWarningType value) {
        this.dataQualityWarning = value;
    }

    /**
     * Gets the value of the dataRole property.
     * 
     * @return
     *     possible object is
     *     {@link DataRoleType }
     *     
     */
    public DataRoleType getDataRole() {
        return dataRole;
    }

    /**
     * Sets the value of the dataRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataRoleType }
     *     
     */
    public void setDataRole(DataRoleType value) {
        this.dataRole = value;
    }

    /**
     * Gets the value of the database property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseType }
     *     
     */
    public DatabaseType getDatabase() {
        return database;
    }

    /**
     * Sets the value of the database property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseType }
     *     
     */
    public void setDatabase(DatabaseType value) {
        this.database = value;
    }

    /**
     * Gets the value of the datasource property.
     * 
     * @return
     *     possible object is
     *     {@link DataSourceType }
     *     
     */
    public DataSourceType getDatasource() {
        return datasource;
    }

    /**
     * Sets the value of the datasource property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSourceType }
     *     
     */
    public void setDatasource(DataSourceType value) {
        this.datasource = value;
    }

    /**
     * Gets the value of the distinctValues property.
     * 
     * @return
     *     possible object is
     *     {@link DistinctValueListType }
     *     
     */
    public DistinctValueListType getDistinctValues() {
        return distinctValues;
    }

    /**
     * Sets the value of the distinctValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistinctValueListType }
     *     
     */
    public void setDistinctValues(DistinctValueListType value) {
        this.distinctValues = value;
    }

    /**
     * Gets the value of the favorite property.
     * 
     * @return
     *     possible object is
     *     {@link FavoriteType }
     *     
     */
    public FavoriteType getFavorite() {
        return favorite;
    }

    /**
     * Sets the value of the favorite property.
     * 
     * @param value
     *     allowed object is
     *     {@link FavoriteType }
     *     
     */
    public void setFavorite(FavoriteType value) {
        this.favorite = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link FieldType }
     *     
     */
    public FieldType getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldType }
     *     
     */
    public void setField(FieldType value) {
        this.field = value;
    }

    /**
     * Gets the value of the fieldConcept property.
     * 
     * @return
     *     possible object is
     *     {@link FieldConceptType }
     *     
     */
    public FieldConceptType getFieldConcept() {
        return fieldConcept;
    }

    /**
     * Sets the value of the fieldConcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldConceptType }
     *     
     */
    public void setFieldConcept(FieldConceptType value) {
        this.fieldConcept = value;
    }

    /**
     * Gets the value of the flow property.
     * 
     * @return
     *     possible object is
     *     {@link FlowType }
     *     
     */
    public FlowType getFlow() {
        return flow;
    }

    /**
     * Sets the value of the flow property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlowType }
     *     
     */
    public void setFlow(FlowType value) {
        this.flow = value;
    }

    /**
     * Gets the value of the flowWarnings property.
     * 
     * @return
     *     possible object is
     *     {@link FlowWarningsListContainerType }
     *     
     */
    public FlowWarningsListContainerType getFlowWarnings() {
        return flowWarnings;
    }

    /**
     * Sets the value of the flowWarnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlowWarningsListContainerType }
     *     
     */
    public void setFlowWarnings(FlowWarningsListContainerType value) {
        this.flowWarnings = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link GroupType }
     *     
     */
    public GroupType getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupType }
     *     
     */
    public void setGroup(GroupType value) {
        this.group = value;
    }

    /**
     * Gets the value of the metric property.
     * 
     * @return
     *     possible object is
     *     {@link MetricType }
     *     
     */
    public MetricType getMetric() {
        return metric;
    }

    /**
     * Sets the value of the metric property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetricType }
     *     
     */
    public void setMetric(MetricType value) {
        this.metric = value;
    }

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link PermissionsType }
     *     
     */
    public PermissionsType getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermissionsType }
     *     
     */
    public void setPermissions(PermissionsType value) {
        this.permissions = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectType }
     *     
     */
    public ProjectType getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectType }
     *     
     */
    public void setProject(ProjectType value) {
        this.project = value;
    }

    /**
     * Gets the value of the schedule property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleType }
     *     
     */
    public ScheduleType getSchedule() {
        return schedule;
    }

    /**
     * Sets the value of the schedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleType }
     *     
     */
    public void setSchedule(ScheduleType value) {
        this.schedule = value;
    }

    /**
     * Gets the value of the site property.
     * 
     * @return
     *     possible object is
     *     {@link SiteType }
     *     
     */
    public SiteType getSite() {
        return site;
    }

    /**
     * Sets the value of the site property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiteType }
     *     
     */
    public void setSite(SiteType value) {
        this.site = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link TableType }
     *     
     */
    public TableType getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableType }
     *     
     */
    public void setTable(TableType value) {
        this.table = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link TagListType }
     *     
     */
    public TagListType getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagListType }
     *     
     */
    public void setTags(TagListType value) {
        this.tags = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setUser(UserType value) {
        this.user = value;
    }

    /**
     * Gets the value of the webhook property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookType }
     *     
     */
    public WebhookType getWebhook() {
        return webhook;
    }

    /**
     * Sets the value of the webhook property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookType }
     *     
     */
    public void setWebhook(WebhookType value) {
        this.webhook = value;
    }

    /**
     * Gets the value of the workbook property.
     * 
     * @return
     *     possible object is
     *     {@link WorkbookType }
     *     
     */
    public WorkbookType getWorkbook() {
        return workbook;
    }

    /**
     * Sets the value of the workbook property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkbookType }
     *     
     */
    public void setWorkbook(WorkbookType value) {
        this.workbook = value;
    }

    /**
     * Gets the value of the subscription property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionType }
     *     
     */
    public SubscriptionType getSubscription() {
        return subscription;
    }

    /**
     * Sets the value of the subscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionType }
     *     
     */
    public void setSubscription(SubscriptionType value) {
        this.subscription = value;
    }

    /**
     * Gets the value of the task property.
     * 
     * @return
     *     possible object is
     *     {@link TaskType }
     *     
     */
    public TaskType getTask() {
        return task;
    }

    /**
     * Sets the value of the task property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskType }
     *     
     */
    public void setTask(TaskType value) {
        this.task = value;
    }

}
