//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//


package com.byldworks.tableau.deploy.api.rest.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for valueSourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="valueSourceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="datasourceValueStore" type="{http://tableau.com/api}dataSourceValueStoreType" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "valueSourceType", propOrder = {
    "datasourceValueStore"
})
public class ValueSourceType {

    protected DataSourceValueStoreType datasourceValueStore;

    /**
     * Gets the value of the datasourceValueStore property.
     * 
     * @return
     *     possible object is
     *     {@link DataSourceValueStoreType }
     *     
     */
    public DataSourceValueStoreType getDatasourceValueStore() {
        return datasourceValueStore;
    }

    /**
     * Sets the value of the datasourceValueStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSourceValueStoreType }
     *     
     */
    public void setDatasourceValueStore(DataSourceValueStoreType value) {
        this.datasourceValueStore = value;
    }

}
