//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//


package com.byldworks.tableau.deploy.api.rest.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for webhookSourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="webhookSourceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="webhook-source-event-datasource-refresh-started" type="{http://tableau.com/api}webhookSourceEventDatasourceRefreshStartedType"/&gt;
 *         &lt;element name="webhook-source-event-datasource-refresh-succeeded" type="{http://tableau.com/api}webhookSourceEventDatasourceRefreshSucceededType"/&gt;
 *         &lt;element name="webhook-source-event-datasource-refresh-failed" type="{http://tableau.com/api}webhookSourceEventDatasourceRefreshFailedType"/&gt;
 *         &lt;element name="webhook-source-event-datasource-updated" type="{http://tableau.com/api}webhookSourceEventDatasourceUpdatedType"/&gt;
 *         &lt;element name="webhook-source-event-datasource-created" type="{http://tableau.com/api}webhookSourceEventDatasourceCreatedType"/&gt;
 *         &lt;element name="webhook-source-event-datasource-deleted" type="{http://tableau.com/api}webhookSourceEventDatasourceDeletedType"/&gt;
 *         &lt;element name="webhook-source-event-workbook-updated" type="{http://tableau.com/api}webhookSourceEventWorkbookUpdatedType"/&gt;
 *         &lt;element name="webhook-source-event-workbook-created" type="{http://tableau.com/api}webhookSourceEventWorkbookCreatedType"/&gt;
 *         &lt;element name="webhook-source-event-workbook-deleted" type="{http://tableau.com/api}webhookSourceEventWorkbookDeletedType"/&gt;
 *         &lt;element name="webhook-source-event-view-deleted" type="{http://tableau.com/api}webhookSourceEventViewDeletedType"/&gt;
 *         &lt;element name="webhook-source-event-workbook-refresh-started" type="{http://tableau.com/api}webhookSourceEventWorkbookRefreshStartedType"/&gt;
 *         &lt;element name="webhook-source-event-workbook-refresh-succeeded" type="{http://tableau.com/api}webhookSourceEventWorkbookRefreshSucceededType"/&gt;
 *         &lt;element name="webhook-source-event-workbook-refresh-failed" type="{http://tableau.com/api}webhookSourceEventWorkbookRefreshFailedType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "webhookSourceType", propOrder = {
    "webhookSourceEventDatasourceRefreshStarted",
    "webhookSourceEventDatasourceRefreshSucceeded",
    "webhookSourceEventDatasourceRefreshFailed",
    "webhookSourceEventDatasourceUpdated",
    "webhookSourceEventDatasourceCreated",
    "webhookSourceEventDatasourceDeleted",
    "webhookSourceEventWorkbookUpdated",
    "webhookSourceEventWorkbookCreated",
    "webhookSourceEventWorkbookDeleted",
    "webhookSourceEventViewDeleted",
    "webhookSourceEventWorkbookRefreshStarted",
    "webhookSourceEventWorkbookRefreshSucceeded",
    "webhookSourceEventWorkbookRefreshFailed"
})
public class WebhookSourceType {

    @XmlElement(name = "webhook-source-event-datasource-refresh-started")
    protected WebhookSourceEventDatasourceRefreshStartedType webhookSourceEventDatasourceRefreshStarted;
    @XmlElement(name = "webhook-source-event-datasource-refresh-succeeded")
    protected WebhookSourceEventDatasourceRefreshSucceededType webhookSourceEventDatasourceRefreshSucceeded;
    @XmlElement(name = "webhook-source-event-datasource-refresh-failed")
    protected WebhookSourceEventDatasourceRefreshFailedType webhookSourceEventDatasourceRefreshFailed;
    @XmlElement(name = "webhook-source-event-datasource-updated")
    protected WebhookSourceEventDatasourceUpdatedType webhookSourceEventDatasourceUpdated;
    @XmlElement(name = "webhook-source-event-datasource-created")
    protected WebhookSourceEventDatasourceCreatedType webhookSourceEventDatasourceCreated;
    @XmlElement(name = "webhook-source-event-datasource-deleted")
    protected WebhookSourceEventDatasourceDeletedType webhookSourceEventDatasourceDeleted;
    @XmlElement(name = "webhook-source-event-workbook-updated")
    protected WebhookSourceEventWorkbookUpdatedType webhookSourceEventWorkbookUpdated;
    @XmlElement(name = "webhook-source-event-workbook-created")
    protected WebhookSourceEventWorkbookCreatedType webhookSourceEventWorkbookCreated;
    @XmlElement(name = "webhook-source-event-workbook-deleted")
    protected WebhookSourceEventWorkbookDeletedType webhookSourceEventWorkbookDeleted;
    @XmlElement(name = "webhook-source-event-view-deleted")
    protected WebhookSourceEventViewDeletedType webhookSourceEventViewDeleted;
    @XmlElement(name = "webhook-source-event-workbook-refresh-started")
    protected WebhookSourceEventWorkbookRefreshStartedType webhookSourceEventWorkbookRefreshStarted;
    @XmlElement(name = "webhook-source-event-workbook-refresh-succeeded")
    protected WebhookSourceEventWorkbookRefreshSucceededType webhookSourceEventWorkbookRefreshSucceeded;
    @XmlElement(name = "webhook-source-event-workbook-refresh-failed")
    protected WebhookSourceEventWorkbookRefreshFailedType webhookSourceEventWorkbookRefreshFailed;

    /**
     * Gets the value of the webhookSourceEventDatasourceRefreshStarted property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventDatasourceRefreshStartedType }
     *     
     */
    public WebhookSourceEventDatasourceRefreshStartedType getWebhookSourceEventDatasourceRefreshStarted() {
        return webhookSourceEventDatasourceRefreshStarted;
    }

    /**
     * Sets the value of the webhookSourceEventDatasourceRefreshStarted property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventDatasourceRefreshStartedType }
     *     
     */
    public void setWebhookSourceEventDatasourceRefreshStarted(WebhookSourceEventDatasourceRefreshStartedType value) {
        this.webhookSourceEventDatasourceRefreshStarted = value;
    }

    /**
     * Gets the value of the webhookSourceEventDatasourceRefreshSucceeded property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventDatasourceRefreshSucceededType }
     *     
     */
    public WebhookSourceEventDatasourceRefreshSucceededType getWebhookSourceEventDatasourceRefreshSucceeded() {
        return webhookSourceEventDatasourceRefreshSucceeded;
    }

    /**
     * Sets the value of the webhookSourceEventDatasourceRefreshSucceeded property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventDatasourceRefreshSucceededType }
     *     
     */
    public void setWebhookSourceEventDatasourceRefreshSucceeded(WebhookSourceEventDatasourceRefreshSucceededType value) {
        this.webhookSourceEventDatasourceRefreshSucceeded = value;
    }

    /**
     * Gets the value of the webhookSourceEventDatasourceRefreshFailed property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventDatasourceRefreshFailedType }
     *     
     */
    public WebhookSourceEventDatasourceRefreshFailedType getWebhookSourceEventDatasourceRefreshFailed() {
        return webhookSourceEventDatasourceRefreshFailed;
    }

    /**
     * Sets the value of the webhookSourceEventDatasourceRefreshFailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventDatasourceRefreshFailedType }
     *     
     */
    public void setWebhookSourceEventDatasourceRefreshFailed(WebhookSourceEventDatasourceRefreshFailedType value) {
        this.webhookSourceEventDatasourceRefreshFailed = value;
    }

    /**
     * Gets the value of the webhookSourceEventDatasourceUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventDatasourceUpdatedType }
     *     
     */
    public WebhookSourceEventDatasourceUpdatedType getWebhookSourceEventDatasourceUpdated() {
        return webhookSourceEventDatasourceUpdated;
    }

    /**
     * Sets the value of the webhookSourceEventDatasourceUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventDatasourceUpdatedType }
     *     
     */
    public void setWebhookSourceEventDatasourceUpdated(WebhookSourceEventDatasourceUpdatedType value) {
        this.webhookSourceEventDatasourceUpdated = value;
    }

    /**
     * Gets the value of the webhookSourceEventDatasourceCreated property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventDatasourceCreatedType }
     *     
     */
    public WebhookSourceEventDatasourceCreatedType getWebhookSourceEventDatasourceCreated() {
        return webhookSourceEventDatasourceCreated;
    }

    /**
     * Sets the value of the webhookSourceEventDatasourceCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventDatasourceCreatedType }
     *     
     */
    public void setWebhookSourceEventDatasourceCreated(WebhookSourceEventDatasourceCreatedType value) {
        this.webhookSourceEventDatasourceCreated = value;
    }

    /**
     * Gets the value of the webhookSourceEventDatasourceDeleted property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventDatasourceDeletedType }
     *     
     */
    public WebhookSourceEventDatasourceDeletedType getWebhookSourceEventDatasourceDeleted() {
        return webhookSourceEventDatasourceDeleted;
    }

    /**
     * Sets the value of the webhookSourceEventDatasourceDeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventDatasourceDeletedType }
     *     
     */
    public void setWebhookSourceEventDatasourceDeleted(WebhookSourceEventDatasourceDeletedType value) {
        this.webhookSourceEventDatasourceDeleted = value;
    }

    /**
     * Gets the value of the webhookSourceEventWorkbookUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventWorkbookUpdatedType }
     *     
     */
    public WebhookSourceEventWorkbookUpdatedType getWebhookSourceEventWorkbookUpdated() {
        return webhookSourceEventWorkbookUpdated;
    }

    /**
     * Sets the value of the webhookSourceEventWorkbookUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventWorkbookUpdatedType }
     *     
     */
    public void setWebhookSourceEventWorkbookUpdated(WebhookSourceEventWorkbookUpdatedType value) {
        this.webhookSourceEventWorkbookUpdated = value;
    }

    /**
     * Gets the value of the webhookSourceEventWorkbookCreated property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventWorkbookCreatedType }
     *     
     */
    public WebhookSourceEventWorkbookCreatedType getWebhookSourceEventWorkbookCreated() {
        return webhookSourceEventWorkbookCreated;
    }

    /**
     * Sets the value of the webhookSourceEventWorkbookCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventWorkbookCreatedType }
     *     
     */
    public void setWebhookSourceEventWorkbookCreated(WebhookSourceEventWorkbookCreatedType value) {
        this.webhookSourceEventWorkbookCreated = value;
    }

    /**
     * Gets the value of the webhookSourceEventWorkbookDeleted property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventWorkbookDeletedType }
     *     
     */
    public WebhookSourceEventWorkbookDeletedType getWebhookSourceEventWorkbookDeleted() {
        return webhookSourceEventWorkbookDeleted;
    }

    /**
     * Sets the value of the webhookSourceEventWorkbookDeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventWorkbookDeletedType }
     *     
     */
    public void setWebhookSourceEventWorkbookDeleted(WebhookSourceEventWorkbookDeletedType value) {
        this.webhookSourceEventWorkbookDeleted = value;
    }

    /**
     * Gets the value of the webhookSourceEventViewDeleted property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventViewDeletedType }
     *     
     */
    public WebhookSourceEventViewDeletedType getWebhookSourceEventViewDeleted() {
        return webhookSourceEventViewDeleted;
    }

    /**
     * Sets the value of the webhookSourceEventViewDeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventViewDeletedType }
     *     
     */
    public void setWebhookSourceEventViewDeleted(WebhookSourceEventViewDeletedType value) {
        this.webhookSourceEventViewDeleted = value;
    }

    /**
     * Gets the value of the webhookSourceEventWorkbookRefreshStarted property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventWorkbookRefreshStartedType }
     *     
     */
    public WebhookSourceEventWorkbookRefreshStartedType getWebhookSourceEventWorkbookRefreshStarted() {
        return webhookSourceEventWorkbookRefreshStarted;
    }

    /**
     * Sets the value of the webhookSourceEventWorkbookRefreshStarted property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventWorkbookRefreshStartedType }
     *     
     */
    public void setWebhookSourceEventWorkbookRefreshStarted(WebhookSourceEventWorkbookRefreshStartedType value) {
        this.webhookSourceEventWorkbookRefreshStarted = value;
    }

    /**
     * Gets the value of the webhookSourceEventWorkbookRefreshSucceeded property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventWorkbookRefreshSucceededType }
     *     
     */
    public WebhookSourceEventWorkbookRefreshSucceededType getWebhookSourceEventWorkbookRefreshSucceeded() {
        return webhookSourceEventWorkbookRefreshSucceeded;
    }

    /**
     * Sets the value of the webhookSourceEventWorkbookRefreshSucceeded property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventWorkbookRefreshSucceededType }
     *     
     */
    public void setWebhookSourceEventWorkbookRefreshSucceeded(WebhookSourceEventWorkbookRefreshSucceededType value) {
        this.webhookSourceEventWorkbookRefreshSucceeded = value;
    }

    /**
     * Gets the value of the webhookSourceEventWorkbookRefreshFailed property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookSourceEventWorkbookRefreshFailedType }
     *     
     */
    public WebhookSourceEventWorkbookRefreshFailedType getWebhookSourceEventWorkbookRefreshFailed() {
        return webhookSourceEventWorkbookRefreshFailed;
    }

    /**
     * Sets the value of the webhookSourceEventWorkbookRefreshFailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookSourceEventWorkbookRefreshFailedType }
     *     
     */
    public void setWebhookSourceEventWorkbookRefreshFailed(WebhookSourceEventWorkbookRefreshFailedType value) {
        this.webhookSourceEventWorkbookRefreshFailed = value;
    }

}
