//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 03:55:43 PM BST 
//


package com.byldworks.tableau.deploy.api.rest.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for webhookDestinationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="webhookDestinationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="webhook-destination-http" type="{http://tableau.com/api}webhookDestinationHttpType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "webhookDestinationType", propOrder = {
    "webhookDestinationHttp"
})
public class WebhookDestinationType {

    @XmlElement(name = "webhook-destination-http")
    protected WebhookDestinationHttpType webhookDestinationHttp;

    /**
     * Gets the value of the webhookDestinationHttp property.
     * 
     * @return
     *     possible object is
     *     {@link WebhookDestinationHttpType }
     *     
     */
    public WebhookDestinationHttpType getWebhookDestinationHttp() {
        return webhookDestinationHttp;
    }

    /**
     * Sets the value of the webhookDestinationHttp property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebhookDestinationHttpType }
     *     
     */
    public void setWebhookDestinationHttp(WebhookDestinationHttpType value) {
        this.webhookDestinationHttp = value;
    }

}
